# Generated by Django 4.2.21 on 2025-05-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_photos/', verbose_name='Фото филиала'),
        ),
    ]
