# Generated by Django 4.2.21 on 2025-05-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_branch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Клиенты должны быть старше 18 лет.', null=True, verbose_name='Дата рождения'),
        ),
    ]
