# Generated by Django 5.0.1 on 2025-06-05 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_alter_clientprofile_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('assigned', 'Назначена агенту'), ('processing', 'В обработке'), ('completed', 'Завершено (договор создан)'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('client_notes', models.TextField(blank=True, help_text='Любые детали или вопросы, которые вы хотите уточнить.', verbose_name='Примечание от клиента')),
                ('agent_notes', models.TextField(blank=True, help_text='Внутренние пометки для агента.', verbose_name='Примечания агента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='insurance_app.agent', verbose_name='Назначенный агент')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance_app.insurancetype', verbose_name='Желаемый вид страхования')),
            ],
            options={
                'verbose_name': 'Заявка на страхование',
                'verbose_name_plural': 'Заявки на страхование',
                'ordering': ['-created_at'],
            },
        ),
    ]
