# Generated by Django 5.0.1 on 2025-06-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нашей компании', max_length=255, verbose_name='Заголовок страницы О нас')),
                ('content', models.TextField(verbose_name='Содержимое страницы О нас')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Содержимое страницы О нас',
                'verbose_name_plural': 'Содержимое страницы О нас',
            },
        ),
    ]
