# Generated by Django 5.0.1 on 2025-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='mission_text',
            field=models.TextField(blank=True, verbose_name='Текст миссии'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='mission_title',
            field=models.CharField(blank=True, default='Наша миссия', max_length=255, verbose_name='Заголовок миссии'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='values_text',
            field=models.TextField(blank=True, verbose_name='Текст о ценностях (можно использовать HTML для списка)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='values_title',
            field=models.CharField(blank=True, default='Наши ценности:', max_length=255, verbose_name='Заголовок для ценностей'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content',
            field=models.TextField(verbose_name='Основное содержимое страницы О нас'),
        ),
    ]
