# Generated by Django 5.0.1 on 2025-06-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutpagecontent_mission_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CargoTransportation', max_length=255, verbose_name='Название сайта')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный Email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('footer_copyright', models.CharField(blank=True, default='© {year} CargoTransportation. Все права защищены.', max_length=255, verbose_name='Текст копирайта в подвале')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
